### ISSUE TITLE
I made a test post... but how to display it on the homepage?

### ISSUE THREAD

**Issue by machikoyasuda** [machikoyasuda/la-gos#2]
I ran these commands:

`touch pages/machiko_test.md`
(edited the markdown file)
(saved the markdown file)
`gatsby develop`
`gatsby build`
`git add .`
`git commit -m "message"`
`git subtree push --prefix public origin gh-pages`

and then i checked this url:
https://machikoyasuda.github.io/la-gos/machiko_test/index.html

the test post is there!

next step is to make a React component to display the posts on the homepage!

**Comment by pmbanugo** [comment]
I've not seen anything that seemed like it generates links to content automatically, but I'm suspecting the ` html.js` or ` pages\index.js`
